name: views
description: A views library for the flash chat app.
version: 1.0.0
author: Jose Pereira
homepage: www.github.com/hetfdex

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  components:
    path: ../components
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.0

flutter:
  assets:
  - images/
