name: flash_chat_views
description: A views library for the flash chat app.
version: 1.0.0
author: Jose Pereira
homepage: www.github.com/hetfdex

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flash_chat_widgets:
    path: ../widgets
  effective_dart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
