name: components
description: A components library for the flash chat app.
version: 1.0.0
author: Jose Pereira
homepage: www.github.com/hetfdex

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"
  

dependencies:
  animated_text_kit: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.0
